name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Asegúrate de que esto coincida con el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build  # Asegúrate de que este comando coincida con tu script de construcción
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live  # Esto desplegará a tu canal en vivo
        projectId: microproyecto-2-d26ae
